name: bgp-member-management
services:
  # Backend API Service
  - name: bgp-backend
    source_dir: /backend
    run_command: npm start
    build_command: npm install
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 5000
    env:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: JWT_SECRET
        # SECURITY: Set this via deployment platform with a strong random value
        # Generate using: openssl rand -base64 64
        value: "REPLACE_WITH_SECURE_VALUE"
      - key: JWT_EXPIRES_IN
        value: "2h"
      - key: BCRYPT_SALT_ROUNDS
        value: "12"
      - key: RATE_LIMIT_WINDOW_MS
        value: "900000"
      - key: RATE_LIMIT_MAX_REQUESTS
        value: "100"
      - key: CORS_ORIGIN
        # SECURITY: NEVER use "*" in production! Set to your actual frontend URL
        value: "REPLACE_WITH_FRONTEND_URL"
      - key: ADMIN_USERNAME
        # SECURITY: Set via deployment platform
        value: "REPLACE_WITH_ADMIN_USERNAME"
      - key: ADMIN_EMAIL
        # SECURITY: Set via deployment platform
        value: "REPLACE_WITH_ADMIN_EMAIL"
      - key: ADMIN_PASSWORD
        # SECURITY: Set a strong password via deployment platform
        # Must be at least 12 characters with uppercase, lowercase, numbers, and symbols
        value: "REPLACE_WITH_STRONG_PASSWORD"
    health_check:
      http_path: /health

  # Frontend React Service
  - name: bgp-frontend
    source_dir: /frontend
    build_command: npm install && npm run build
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    env:
      - key: REACT_APP_API_URL
        value: "${bgp-backend.PUBLIC_URL}/api"
      - key: REACT_APP_ENVIRONMENT
        value: "production"
    http_port: 3000
    routes:
      - path: /